# Generated by Django 5.2.6 on 2025-09-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(verbose_name='Логин')),
                ('password', models.CharField(verbose_name='Пороль')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
    ]
